### ISSUE TITLE
Improve build resiliency, add more keyservers

### ISSUE THREAD

**Issue by dentarg** [Starkast/heroku-buildpack-cmake#13]
I was alerted that the daily cron build failed (https://travis-ci.com/Starkast/heroku-buildpack-cmake/builds/83575102) and thought I should check it out myself.

Seems like we should have more keyservers to fallback to. (keys.gnupg.net / hkps.pool.sks-keyservers.net are the same pool of servers, see #7)

```
root@3eb102d9ab18:/# gpg --quiet --keyserver keys.gnupg.net --keyserver-options timeout=5 --recv-keys CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA
gpg: requesting key 7BFB4EDA from hkp server keys.gnupg.net
gpgkeys: key CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA can't be retrieved
gpg: no valid OpenPGP data found.
root@3eb102d9ab18:/# echo $?
2

root@3eb102d9ab18:/# gpg --quiet --keyserver hkps.pool.sks-keyservers.net --keyserver-options timeout=5 --recv-keys CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA
gpg: requesting key 7BFB4EDA from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA can't be retrieved
gpg: no valid OpenPGP data found.
root@3eb102d9ab18:/# echo $?
2

root@3eb102d9ab18:/# gpg --quiet --keyserver pgp.mit.edu --keyserver-options timeout=5 --recv-keys CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA
gpg: requesting key 7BFB4EDA from hkp server pgp.mit.edu
root@3eb102d9ab18:/# echo $?
0

root@3eb102d9ab18:/# gpg --quiet --keyserver keyserver.ubuntu.com --keyserver-options timeout=5 --recv-keys CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA
gpg: requesting key 7BFB4EDA from hkp server keyserver.ubuntu.com
root@3eb102d9ab18:/# echo $?
0

root@3eb102d9ab18:/# gpg --quiet --keyserver pool.sks-keyservers.net --keyserver-options timeout=5 --recv-keys CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA
gpg: requesting key 7BFB4EDA from hkp server pool.sks-keyservers.net
root@3eb102d9ab18:/# echo $?
0
```

Related to #6, #7

**Comment by dentarg** [comment]
keys.gnupg.net / hkps.pool.sks-keyservers.net are now working again:

```
root@3eb102d9ab18:/# gpg --quiet --keyserver keys.gnupg.net --keyserver-options timeout=5 --recv-keys CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA
gpg: requesting key 7BFB4EDA from hkp server keys.gnupg.net
root@3eb102d9ab18:/# echo $?
0

root@3eb102d9ab18:/# gpg --quiet --keyserver hkps.pool.sks-keyservers.net --keyserver-options timeout=5 --recv-keys CBA23971357C2E6590D9EFD3EC8FEF3A7BFB4EDA
gpg: requesting key 7BFB4EDA from hkp server hkps.pool.sks-keyservers.net
root@3eb102d9ab18:/# echo $?
0
```

I guess it wasn't working for about 30 minutes? That's no good.

**Comment by dentarg** [comment]
Leaving a comment for myself, how I started the Docker container

    docker run -it --entrypoint "bash" -v $(pwd):/app/buildpack:ro heroku/buildpack-testrunner

**Comment by ashawley** [comment]
After #8, we didn't have the issue on our staging environment, and today the buildpack went to production.  To be fair, staging gets built a lot more often than production.

Is this a possible single point of failure for deploying?  Should there be an emergency override, just in case, that can disable verification?

**Comment by dentarg** [comment]
The Travis CI build has failed two more times since I created this issue. It runs everyday: https://travis-ci.com/Starkast/heroku-buildpack-cmake/builds

So this might not be a big issue. I created the issue just to have somewhere to report on it. Yes, when it fails, it stops the deploy. That might not be a big issue either (just re-try the deploy?). I don't know what an emergency override would look like. I don't think disabling verification is a good idea, even it is just once, temporary.

**Comment by ashawley** [comment]
Yes, there is always the redeploy, but if verification was a broad enough problem it could be unresolvable.

Yeah, I forgot that buildpacks aren't interactive commands, so an override feature isn't really possible.  I guess it would need to be an environment variable or something.

Whether disabling verification is bad is not something I know enough to judge.  I guess I'd have to audit our build and see how many artifacts are or aren't signed, or checksum'd or not at all and weigh that against cmake not being signed.

Anyway, talking this out I'm less inclined to worry about deployment being blocked, so thanks for discussing it and thanks for maintaining the buildpack.

**Comment by dentarg** [comment]
A deploy of my own just failed, looked like this

```
-----> Heroku Exec app detected
-----> CMake app detected
-----> Installing CMake version: 3.8.1
       Downloading binary distribution
       Verifying download
gpg: keyserver receive failed: No data
gpg: keyserver receive failed: No data
gpg: keyserver receive failed: No data
gpg: keyserver receive failed: No data
gpg: Signature made Tue 02 May 2017 01:44:31 PM UTC
gpg:                using RSA key C6C265324BBEBDC350B513D02D2CEF1034921684
gpg: Can't check signature: No public key
 !     Push rejected, failed to compile CMake app.
 !     Push failed
```

**Comment by ashawley** [comment]
Yeah, I was just looking at deploy logs and noticing a few retries, yesterday, but only one or two.  There was never four, enough to result in a failure.

Retrying four times was a pretty good number to guess in #8.  We could grow it to 8 or 10.  Alternatively, we could sleep for a second or two between tries.

PS. I guess there should be an error check at the end of the `recv-key` loop.

**Comment by dentarg** [comment]
https://dev.gnupg.org/T4163 - found someone else that also thinks the HKPS pool (`keys.gnupg.net`/`hkps.pool.sks-keyservers.net`) is a bit unreliable

**Comment by dentarg** [comment]
Found a [decent description](https://bitbucket.org/skskeyserver/sks-keyserver/wiki/TLS%20Configuration) of what the HKPS pool is:

>The keyservers are run by various people with no formal affiliation, as a public good by each person choosing to cooperate. There is no shared organization, no formal responsibility. There are "pool" hostnames, which are maintained by spidering the peering mesh on the "list of peers" info page, and working under a common hostname. https://sks-keyservers.net/overview-of-pools.php has more information.
>
>Thus for hkps, we need "several" different, unaffiliated, people to all have certificates for the same hostname.

From GnuPG 2.1.11 the sks-keyservers.net CA is shipped with GnuPG and enabled by default for that pool, https://sks-keyservers.net/overview-of-pools.php#pool_hkps. [Heroku has GnuPG 2.2.4 installed](https://devcenter.heroku.com/articles/stack-packages).

**Comment by dentarg** [comment]
It might be good enough now, last 5 days are green: https://travis-ci.com/Starkast/heroku-buildpack-cmake/builds

Note that builds on Travis CI times out after 10 minutes. If Heroku allows it, the buildpack will keep trying another 20 minutes.

**Comment by ashawley** [comment]
Hey Patrik,

Looks like you set it to 360 retries with a 5 second timeout and a 5 second delay between retries.  That sounds like it will keep trying for 60 minutes.

**Comment by dentarg** [comment]
True, but I'm not sure in which cases `gpg` uses the given timeout. I'm pretty sure in the examples in my original post here, the commands failed immediately.
