### ISSUE TITLE
key 7BFB4EDA can't be retrieved

### ISSUE THREAD

**Issue by jstanley14** [Starkast/heroku-buildpack-cmake#6]
We previously deployed on Heroku with this buildpack fine, but this morning we are seeing this error:'

remote: gpg: new configuration file `/app/.gnupg/gpg.conf' created
remote: gpg: WARNING: options in `/app/.gnupg/gpg.conf' are not yet active during this run
remote: gpg: requesting key 7BFB4EDA from hkp server pgp.mit.edu
remote: gpgkeys: key 7BFB4EDA can't be retrieved
remote: gpg: no valid OpenPGP data found.
remote: gpg: requesting key 7BFB4EDA from hkp server keys.gnupg.net
remote: gpgkeys: key 7BFB4EDA can't be retrieved
remote: gpg: no valid OpenPGP data found.
remote:  !     Push rejected, failed to compile CMake app.
remote:
remote:  !     Push failed

**Comment by dentarg** [comment]
I believe this issue is temporary (I'm able to run the tests right now).

I haven't looked into how to not needing to rely on the key servers, but I'm happy to review any pull request in that area.
